### PR TITLE
Add pytest and initial tests

### PR DESCRIPTION
**Pull request by cdvv7788**
# Summary

Setup pytest and add happy path tests. In collaboration with @apkallum.

# Changes these areas

- [ ] Bugfixes
- [X] Feature behavior
- [ ] Command line interface
- [ ] Configuration options
- [ ] Internal architecture
- [ ] Archived data layout on disk

### CODE REVIEW

**Comment by pirate** [comment]
Looks good so far, you can use the stdlib to create the temporary directory for the tests: https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory

**Comment by cdvv7788** [comment]
@pirate We are using this fixture https://docs.pytest.org/en/latest/tmpdir.html
It creates a temp dir in the same fashion (built-in in pytest).

**Comment by pirate** [comment]
Cool. Lets setup github actions next to run these tests automatically on pull! (in this same PR)

**Comment by apkallum** [comment]
@pirate Added Github workflow.

**Pull request merged**
