### PR TITLE
Feature: Add @postlight/mercury-parser as an alternative to Readability

### PR DESCRIPTION
**Pull request by ttimasdf**
# Summary

This PR add [mercury-parser](https://github.com/postlight/mercury-parser) as a backend engine to extract meaningful content from HTML, as an alternative to Readability.

> Mercury Parser powers the Mercury AMP Converter and Mercury Reader, a Chrome extension that removes ads and distractions, leaving only text and images for a beautiful reading view on any site.

mercury parser is also used by [Newsblur](https://github.com/samuelclay/NewsBlur), my favorite RSS Reader 😄 

# Changes these areas

- [ ] Bugfixes
- [x] Feature behavior
- [ ] Command line interface
- [x] Configuration options
- [ ] Internal architecture
- [x] Archived data layout on disk

# Motivation

I'm trying to archive this article. https://bbs.pediy.com/thread-229215.htm

Readability could only extract the last code block inside this article.

image

image

Mercury Parser is able to extract the whole content

image

### CODE REVIEW

**Comment by ttimasdf** [comment]
Added one more row but it looks a bit weird... 🤔 
image

**Comment by ttimasdf** [comment]
I also tried to let mercury get input from `singlepage.html` content, but it yielded a different result (i.e. not working). I add another wrapper script for testing. https://github.com/ttimasdf/ArchiveBox/commit/78477dc387908677fb65c7d0f1b09edd1063d970

**Comment by cdvv7788** [comment]
This looks pretty good. @pirate should I merge it? I am missing some more manual testing, but the PR looks good to me.

**Comment by pirate** [comment]
This looks great! I'm going to merge it, we can fix any further issues in PRs off `master`. Thank you so much for this work @ttimasdf!

**Pull request merged**
