### PR TITLE
Add a bookmarklet

### PR DESCRIPTION
**Pull request by adamwolf**
# Summary

The bookmarklet lets you quickly open the Add page with the URL already populated in the URLs box.

# Changes these areas

- [ ] Bugfixes
- [x] Feature behavior
- [ ] Command line interface
- [ ] Configuration options
- [ ] Internal architecture
- [ ] Archived data layout on disk

### CODE REVIEW

**Comment by adamwolf** [comment]
Hi folks!

I added a bookmarklet to help me add things to my ArchiveBox.

I am not a Django expert anymore. I do not quite know what is going on in admin.py's `add_view`. I am not sure it's currently being used.  It looks like maybe it's being bypassed and turned into a redirect to `AddView` in `urls.py`.  If there's something I missed there, and it is being used, it should probably get an adjustment to pull in the initial form data like `AddView`.  I'd be glad to do that, of course!

This isn't the absolute lowest effort way (for users) to have your browser archive the current page. It opens the Add page with the URLs box prefilled with your last page. I would like to create a Chrome/Firefox/Safari extension, especially if that's something you're are interested in. If anyone besides Google picks up something like the Web Share Target API, I'd love to bring that in as well.

**Review by pirate — APPROVED** [review]

**Comment by pirate** [comment]
Great idea, thanks! This has been wanted for a long time and this solution seems simple and functional enough for a first-pass attempt.

**Comment by raidancampbell** [comment]
Would it be feasible to cut a release soon?  This feature is a huge benefit for general usability, and the most recent releases are a couple months old.

**Comment by pirate** [comment]
The new release is going out as soon as #502 is merged and tested thoroughly, eta 1-2 weeks depending on my schedule next week.

In the meantime, you should be able to use the master branch without too much difficulty:
```bash
git clone https://github.com/pirate/ArchiveBox && cd Archivebox
git checkout master && git pull

docker build . -t archivebox
docker run -v $PWD:/data -it archivebox ...

# or
pip install -e .
```

**Comment by adamwolf** [comment]
pirate, if you don't mind, would you tag this PR as "hacktoberfest-accepted"? If you do mind, no problem and I'm sorry for asking :) My kiddos like the shirts...

**Pull request merged**
