### PR TITLE
i have no idea what im doing

### PR DESCRIPTION
**Pull request by jonconnor67**
but i'd love to use this service because archive.org keeps deleting my articles

**IMPORTANT: Do not submit PRs with only formatting / PEP8 / line length changes, I will close them with great prejudice.  The PEP8 checks I don't follow are intentional. PRs for minor bugfixes, typos, etc are fine.**

# Summary

e.g. This PR fixes ABC or adds the ability to do XYZ...

**Related issues: #XYZ** (delete this line if there are no related issues)

# Changes these areas

- [ ] Bugfixes
- [ ] Feature behavior
- [ ] Command line interface
- [ ] Configuration options
- [ ] Internal architecture
- [ ] Archived data layout on disk

# Roadmap Goals

This PR helps us move towards xyz roadmap goal, as outlined here: https://github.com/pirate/ArchiveBox#roadmap
(delete this section if it's just a bugfix / simple PR)

### CODE REVIEW

**Comment by pirate** [comment]
wat.

**Comment by jonconnor67** [comment]
Common don;'t be obtuse.  Seriously, archive.org is deleting my article.  Please help me...

**Comment by jonconnor67** [comment]
> wat.
Please help me, I can't figure out how to use it..

**Comment by pirate** [comment]
I'm happy to help, but I need more information.

what end goal are you trying to achieve? 
what commands have you tried running so far?
where are the urls that you want to archive coming from?

Are you looking for a command line tool or a web UI or a native app?
Have you tried any other archiving tools e.g. https://github.com/pirate/ArchiveBox/wiki/Web-Archiving-Community#Projects

**Comment by jonconnor67** [comment]
> I'm happy to help, but you need to give more information when you open tickets. We're not mind readers and opening 3 identical tickets doesn't make the process go faster.
> 
> what end goal are you trying to achieve?
> where are the urls that you want to archive coming from?
> Are you looking for a command line tool or a web UI or a native app?
> what commands have you tried running so far? did you get stuck on the quickstart somewhere?
> are you looking for links to documentation, tutorials, 1:1 support call?
> Have you tried any other archiving tools e.g. https://github.com/pirate/ArchiveBox/wiki/Web-Archiving-Community#Projects

Thanks for the reply!!
I've downloaded github, and downloaded archivebox into github...but do I need to download software other than github?  Sorry I've never coded before, and I suspect the Way Back Machine has become compromised.

**Comment by jonconnor67** [comment]
> I'm happy to help, but you need to give more information when you open tickets. We're not mind readers and opening 3 identical tickets doesn't make the process go faster.
> 
> what end goal are you trying to achieve?
> where are the urls that you want to archive coming from?
> Are you looking for a command line tool or a web UI or a native app?
> what commands have you tried running so far? did you get stuck on the quickstart somewhere?
> are you looking for links to documentation, tutorials, 1:1 support call?
> Have you tried any other archiving tools e.g. https://github.com/pirate/ArchiveBox/wiki/Web-Archiving-Community#Projects

My operating system doesn't support Docker because it's too old, so I don't know what to do..

**Comment by pirate** [comment]
> Sorry I've never coded before

@jonconnor67 I don't think this is the ideal tool for you then, there's a bit of terminal setup required and it's likely to be more trouble than it's worth.

Try one of the alternatives here instead: https://github.com/pirate/ArchiveBox/wiki/Web-Archiving-Community#Web-Archiving-Projects

In particular I recommend [SiteSucker](https://ricks-apps.com/osx/sitesucker/), [WebRecorder](https://github.com/webrecorder/webrecorder-desktop#webrecorder-desktop-app), [SingleFile](https://chrome.google.com/webstore/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle?hl=en).

**Pull request closed without merging**
